on:
  schedule:
    - cron: "30 2 * * *"   # 2:30 UTC

jobs:
  test-r:
    runs-on: ubuntu-latest
    name: A job to test R
    steps:
      - name: Test R action step
        id: test
        uses: davidcurrie2001/RDockerTest@main

